name: PR Title

on:
  pull_request_target:
    types: [opened, edited, synchronize, reopened]

jobs:
  lint-title:
    name: Enforce Conventional PR Title
    permissions:
      pull-requests: read
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            docs
            style
            refactor
            perf
            test
            build
            chore
            ci
          requireScope: false
          subjectPattern: ^[a-z].+[^\.]$
          subjectPatternError: "Subject must be lowercase, imperative, no trailing period"

